"""ZAP integration for guideline 2-1 — same upload probe matrix over ZAP sendRequest.

Auth headers are attached explicitly per-request (same as the httpx phase) —
ZAP's Replacer is not needed here because every probe is sent via
``zap.core.sendRequest`` with our own headers already in the raw request, not
generated by ZAP itself (unlike spider/active-scan crawling, which does need
the Replacer). Routing through ZAP means every probe lands in ZAP's
Sites/History and gets passively scanned like normal proxied traffic, so we
piggy-back on ZAP's own passive rules (e.g. X-Content-Type-Options missing,
Directory Browsing) as a supplemental signal on top of our own findings.
"""

from __future__ import annotations

from typing import Any

from app.services.zap_util import (
    apply_auth_to_zap,
    connect_zap,
    ensure_zap_proxy,
    probe_url,
    reset_zap_workspace,
)

# Re-exported for scanner.py, which accesses it as `zap_scan_mod.wait_for_passive_scan`
# (sibling modules here are loaded dynamically via importlib, not imported directly).
from app.services.zap_util import wait_for_passive_scan as wait_for_passive_scan
from diagnosis.probe_transport import ZapTransport
from diagnosis.result import DiagnosisFinding

PLUGIN_LABELS: dict[str, str] = {
    "0": "ZAP Rule 0 (Directory Browsing)",
    "10033": "ZAP Rule 10033 (Directory Browsing, passive)",
    "40035": "ZAP Rule 40035 (Hidden File Finder)",
    "10021": "ZAP Rule 10021 (X-Content-Type-Options Missing)",
    "10054": "ZAP Rule 10054 (Cookie without SameSite)",
    "10096": "ZAP Rule 10096 (Timestamp Disclosure)",
    "10027": "ZAP Rule 10027 (Suspicious Comments)",
    "10023": "ZAP Rule 10023 (Information Disclosure — Debug Error)",
}

_SEVERITY_BY_RISK = {"high": "high", "medium": "medium", "low": "low", "informational": "info"}


def open_zap_transport(
    raw_config: dict[str, Any],
    auth: dict[str, Any] | None = None,
) -> tuple[Any, ZapTransport, str]:
    """Connect to ZAP and return (zap_client, transport, proxy_url).

    auth를 전달하면 ZAP Replacer에 인증 헤더를 주입해 passive 규칙이
    인증된 응답도 분석할 수 있도록 한다.

    Raises ``ZapNotAvailableError`` (from ``app.services.zap_util``) when ZAP
    cannot be reached — callers should catch that and degrade to httpx-only.
    """
    zap_cfg = raw_config.get("zap") or {}
    proxy = ensure_zap_proxy(zap_cfg)
    zap = connect_zap(proxy, str(zap_cfg.get("api_key") or ""))
    if auth:
        apply_auth_to_zap(zap, auth)
    return zap, ZapTransport(zap), proxy


def collect_supplemental_findings(
    zap: Any,
    probed_urls: set[str],
) -> list[DiagnosisFinding]:
    """Native ZAP alerts recorded on our own probed URLs (not the whole site)."""
    if not probed_urls:
        return []

    bases = {probe_url(u).split("?", 1)[0].rsplit("/", 1)[0] or "/" for u in probed_urls}
    normalized_targets = {probe_url(u).split("?", 1)[0] for u in probed_urls}

    findings: list[DiagnosisFinding] = []
    seen: set[str] = set()
    seen_bases: set[str] = set()

    for base in bases:
        origin = base.split("/", 3)
        origin_key = "/".join(origin[:3]) if len(origin) >= 3 else base
        if origin_key in seen_bases:
            continue
        seen_bases.add(origin_key)
        try:
            alerts = zap.core.alerts(baseurl=origin_key)
        except Exception:
            alerts = []
        for alert in alerts or []:
            if not isinstance(alert, dict):
                continue
            url = str(alert.get("url") or "").split("?", 1)[0]
            if url not in normalized_targets:
                continue
            plugin_id = str(alert.get("pluginId", ""))
            dedupe = f"{plugin_id}:{url}:{alert.get('param')}"
            if dedupe in seen:
                continue
            seen.add(dedupe)
            risk = str(alert.get("risk", "")).lower()
            findings.append(
                DiagnosisFinding(
                    severity=_SEVERITY_BY_RISK.get(risk, "info"),
                    message=(
                        f"[2-1][zap-native] {alert.get('alert', alert.get('name', 'ZAP alert'))} "
                        f"— {url}"
                    ),
                    evidence={
                        "rule_id": "2-1-zap-supplemental",
                        "engine": "zap",
                        "source": "zap",
                        "analysis_mode": "native",
                        "plugin_id": plugin_id,
                        "trigger_label": PLUGIN_LABELS.get(plugin_id, f"ZAP Rule {plugin_id}"),
                        "url": alert.get("url"),
                        "param": alert.get("param"),
                        "risk": alert.get("risk"),
                        "evidence": alert.get("evidence"),
                    },
                )
            )
    return findings


def reset_workspace(zap: Any, *, session_name: str) -> dict[str, Any]:
    return reset_zap_workspace(zap, session_name=session_name)
